I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/d11.rpy", line 66, in script
    jump d12
ScriptError: could not find label 'd12'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/d11.rpy", line 66, in script
    jump d12
  File "D:\Program Files\renpy-8.2.1-sdk\renpy\ast.py", line 1698, in execute
    rv = renpy.game.script.lookup(target)
  File "D:\Program Files\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'd12'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
casanoba project 1.0
Mon Jul 15 05:04:47 2024
