I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/d6_d7_d8_d9.rpy", line 59, in script
    python:
  File "game/d6_d7_d8_d9.rpy", line 60, in <module>
    gchoice = food_list[0]
NameError: name 'food_list' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/d6_d7_d8_d9.rpy", line 59, in script
    python:
  File "A:\Renpy\renpy-8.2.1-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "A:\Renpy\renpy-8.2.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/d6_d7_d8_d9.rpy", line 60, in <module>
    gchoice = food_list[0]
NameError: name 'food_list' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
casanoba project 1.0
Sun Jun 23 01:09:31 2024
