I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/d6_d7_d8_d9.rpy", line 151, in script
    jump d11
ScriptError: could not find label 'd10'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/d6_d7_d8_d9.rpy", line 151, in script
    jump d11
  File "A:\Renpy\renpy-8.2.1-sdk\renpy\ast.py", line 1698, in execute
    rv = renpy.game.script.lookup(target)
  File "A:\Renpy\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'd10'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
casanoba project 1.0
Mon Jun 24 05:02:03 2024
