I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/h2.rpy", line 2, in script
    play sound 짹짹
  File "renpy/common/000statements.rpy", line 301, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 33, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/h2.rpy", line 2, in <module>
    play sound 짹짹
NameError: name '짹짹' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/h2.rpy", line 2, in script
    play sound 짹짹
  File "C:\Users\박민경\Desktop\렝파이\renpy-8.2.1-sdk\renpy\ast.py", line 1968, in execute
    self.call("execute")
  File "C:\Users\박민경\Desktop\렝파이\renpy-8.2.1-sdk\renpy\ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\박민경\Desktop\렝파이\renpy-8.2.1-sdk\renpy\statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 301, in execute_play_sound
    renpy.sound.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 33, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "C:\Users\박민경\Desktop\렝파이\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\박민경\Desktop\렝파이\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/h2.rpy", line 2, in <module>
    play sound 짹짹
NameError: name '짹짹' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
casanoba project 1.0
Fri Jun 21 04:39:54 2024
